language: node_js
node_js: 10
cache: yarn

os:
- osx
- linux

script:
- |
  echo ">>> Compile vscode-test"
  yarn && yarn compile
  echo ">>> Compiled vscode-test"

after_script:
- |
  echo ">>> Publish"
  yarn deploy

stages:
- name: after_script
  if: env(TRAVIS_TAG) =~ ^v

env:
  global:
    secure: cS2ToftgA9f1FAs+qKyy+wls/klDgiKa7lA5vHi4z5ZMS3vv7dLewofMcQLxvr4CEkNL7uDtYcvR8ebb3mGN4eQzGOnUJ0VOpo0S5WXklXtdjZknX3E6isfU2uwVQRwHhD4BQSEHC9kPI/WX08Xsz3S6xeQkL1xrvPlTMZVYTXCztOF3g6sLMX9W5mweJYmUnIbMbClseFUYUbrXY8dI9QkvonWGXiYC3cZ8orWRai6jmAZu2kHBhmQyadK2C9ckOG7gNq7bZMvI9jbtCyhhrGLJDH8Nguf2DN2tWgaGEcLHrrHHTu1iT9qV3pkH1xmBVn2dQfXzXgTkq+A+eXHnLRrq6e1e0lARrITDW0a16r9P0Cw5t7IbOHfJO+EUZrPluf7hNljzJQBzumTY5Iy/7xBhU7806zefj5LG7UM2tOyluJwbQdPrq607m0Buu9ziDqTP6+72dLDnDtNJvwCSLmZx5rbDwnPA6ZoAkYuC7WjgX2Rq09MJhNQH+6OecyDREAsXh1LO1G10j/f3cqe7Z2OlpFd8Uv1deZDxvFUrehUIPgD8Oy1P3EGgcBbRaCi5WBnPV+DqRuMfXtiAYAjrQcLq4SY/5DmG3u9k4Kt8ZGdOATstBCYOFs+1LH62uSDRscXAX0KgQ8vmGVPIgkurXC5ISF731J5uCCQlTlxiLxY=
