on: [push]

jobs:
  main:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: yarn
    - run: yarn compile
    - run: yarn deploy
      if: success() && startsWith(github.ref, 'refs/tags/v')
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
