on:
  push:
    branches:
      - master
  release:
    types:
    - created

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: yarn
    - run: yarn compile
    - name: Publish
      if: success() && startsWith(github.ref, 'refs/tags/v') && matrix.os == 'ubuntu-latest'
      run: yarn deploy
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
